<?php
require_once __DIR__ . '/src/bootstrap.php';
require_auth();
$u = current_user();
if (!$u) { session_unset(); session_destroy(); header('Location: login.php'); exit; }
if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    if (!verify_csrf()) die('csrf');
    if (isset($_POST['new_post'])) db()->prepare('INSERT INTO posts(user_id,body) VALUES(:u,:b)')->execute(['u'=>$u['id'],'b'=>trim($_POST['body'])]);
    if (isset($_POST['share_post'])) { $sid=(int)$_POST['share_post_id']; db()->prepare('INSERT INTO posts(user_id,body,shared_post_id) VALUES(:u,:b,:s)')->execute(['u'=>$u['id'],'b'=>trim($_POST['share_body']??'Shared post'),'s'=>$sid]); $o=db()->prepare('SELECT user_id FROM posts WHERE id=:id');$o->execute(['id'=>$sid]);$owner=$o->fetchColumn(); if($owner&&$owner!=$u['id']) db()->prepare("INSERT INTO notifications(user_id,actor_id,type,ref_type,ref_id,message) VALUES(:uid,:aid,'share','post',:rid,:m)")->execute(['uid'=>$owner,'aid'=>$u['id'],'rid'=>$sid,'m'=>$u['name'].' shared your post']); }
    if (isset($_POST['comment'])) { $pid=(int)$_POST['post_id']; db()->prepare('INSERT INTO comments(post_id,user_id,body) VALUES(:p,:u,:b)')->execute(['p'=>$pid,'u'=>$u['id'],'b'=>trim($_POST['comment_body'])]); $o=db()->prepare('SELECT user_id FROM posts WHERE id=:id');$o->execute(['id'=>$pid]);$owner=$o->fetchColumn(); if($owner&&$owner!=$u['id']) db()->prepare("INSERT INTO notifications(user_id,actor_id,type,ref_type,ref_id,message) VALUES(:uid,:aid,'comment','post',:rid,:m)")->execute(['uid'=>$owner,'aid'=>$u['id'],'rid'=>$pid,'m'=>$u['name'].' commented on your post']); }
    if (isset($_POST['reply'])) { $cid=(int)$_POST['comment_id']; db()->prepare('INSERT INTO replies(comment_id,user_id,body) VALUES(:c,:u,:b)')->execute(['c'=>$cid,'u'=>$u['id'],'b'=>trim($_POST['reply_body'])]); $o=db()->prepare('SELECT user_id FROM comments WHERE id=:id');$o->execute(['id'=>$cid]);$owner=$o->fetchColumn(); if($owner&&$owner!=$u['id']) db()->prepare("INSERT INTO notifications(user_id,actor_id,type,ref_type,ref_id,message) VALUES(:uid,:aid,'reply','comment',:rid,:m)")->execute(['uid'=>$owner,'aid'=>$u['id'],'rid'=>$cid,'m'=>$u['name'].' replied to your comment']); }
    if (isset($_POST['react'])) { $k=$_POST['reaction_key'];$label=$_POST['reaction_label']; if($k==='custom'){$label=trim($_POST['custom_reaction']);$k='custom';} $tt=$_POST['target_type'];$tid=(int)$_POST['target_id']; db()->prepare('INSERT INTO reactions(user_id,target_type,target_id,reaction_key,reaction_label) VALUES(:u,:t,:id,:k,:l) ON DUPLICATE KEY UPDATE reaction_key=VALUES(reaction_key),reaction_label=VALUES(reaction_label)')->execute(['u'=>$u['id'],'t'=>$tt,'id'=>$tid,'k'=>$k,'l'=>$label]); $owner=null; if($tt==='post'){$o=db()->prepare('SELECT user_id FROM posts WHERE id=:id');}elseif($tt==='comment'){$o=db()->prepare('SELECT user_id FROM comments WHERE id=:id');}else{$o=db()->prepare('SELECT user_id FROM replies WHERE id=:id');}$o->execute(['id'=>$tid]);$owner=$o->fetchColumn(); if($owner&&$owner!=$u['id']) db()->prepare("INSERT INTO notifications(user_id,actor_id,type,ref_type,ref_id,message) VALUES(:uid,:aid,'reaction',:rt,:rid,:m)")->execute(['uid'=>$owner,'aid'=>$u['id'],'rt'=>$tt,'rid'=>$tid,'m'=>$u['name'].' reacted to your '.$tt]); }
    header('Location: feed.php'); exit;
}
$posts = db()->query('SELECT p.*,u.name FROM posts p JOIN users u ON u.id=p.user_id ORDER BY p.id DESC LIMIT 40')->fetchAll();
?>
<!doctype html><html><head><meta charset='utf-8'><link rel='stylesheet' href='assets/style.css'><title>Socialize Feed</title></head><body><div class='panel'><div class='container' style='width:min(820px,94vw)'><h1>Socialize Feed</h1><p>Profile: <strong><?=initials($u['name'] ?? '')?></strong></p><form method='post'><input type='hidden' name='csrf_token' value='<?=csrf_token()?>'><textarea name='body' required style='width:100%;height:90px'></textarea><button name='new_post'>Post</button></form><hr>
<?php foreach($posts as $p): ?><div><strong><?=htmlspecialchars($p['name'])?></strong><p><?=nl2br(htmlspecialchars($p['body']))?></p>
<form method='post'><input type='hidden' name='csrf_token' value='<?=csrf_token()?>'><input type='hidden' name='target_type' value='post'><input type='hidden' name='target_id' value='<?=$p['id']?>'><select name='reaction_key'><?php foreach(react_options() as $r):?><option value='<?=$r['key']?>'><?=$r['label']?></option><?php endforeach;?></select><input name='reaction_label' placeholder='label'><input name='custom_reaction' placeholder='custom'><button name='react'>React</button></form>
<form method='post'><input type='hidden' name='csrf_token' value='<?=csrf_token()?>'><input type='hidden' name='post_id' value='<?=$p['id']?>'><input name='comment_body' required><button name='comment'>Comment</button></form>
<form method='post'><input type='hidden' name='csrf_token' value='<?=csrf_token()?>'><input type='hidden' name='share_post_id' value='<?=$p['id']?>'><input name='share_body'><button name='share_post'>Share</button></form></div><?php endforeach; ?></div></div><div id='notifBox' style='position:fixed;right:16px;bottom:16px;background:#06211c;padding:12px;border:1px solid #1f5f50;border-radius:10px;max-width:300px'><strong>Notifications</strong><ul id='notifList' style='padding-left:18px'></ul></div><script>async function loadN(){const r=await fetch('notifications.php');const j=await r.json();document.getElementById('notifList').innerHTML=j.slice(0,5).map(n=>`<li>${n.message}</li>`).join('');}loadN();setInterval(loadN,5000);</script></body></html>
